[window]
opacity = 0.7
blur = true

[shell]
program = "/bin/fish"
args = ["-l"]

[font]
  normal = { family = "SFMono Nerd Font", style = "Regular" }
  bold = { family = "SFMono Nerd Font", style= "Bold" }
  italic = { family="SFMono Nerd Font", style="Italic" }
